FROM frolvlad/alpine-glibc

ENV loglevel=info

RUN apk upgrade --update-cache \
    && apk add dumb-init \
    && rm -rf /var/cache/apk/*

RUN mkdir -p /etc/envoy

ADD envoy-stripped-binary /usr/local/bin/envoy
